### ISSUE TITLE
Missing commas

### ISSUE THREAD

**Issue by myangelkamikaze** [ElectronicObserverEN/Data#13]
@MirhasVida I didn't notice it when you made the PR, but there are missing commas in [expedition.json](https://github.com/ElectronicObserverEN/Data/blob/master/Translations/ko-KR/expedition.json#L245).

**Comment by MirhasVida** [comment]
I've added it, but please let me know if there are still problems.

**Comment by MirhasVida** [comment]
Btw I cannot find any translation files for the UI
Could you make it for me?

**Comment by myangelkamikaze** [comment]
> I've added it, but please let me know if there are still problems.

I don't see any changes related to that, where did you add it?

> Btw I cannot find any translation files for the UI Could you make it for me?

The UI translations are in the [Electronic Observer](https://github.com/ElectronicObserverEN/ElectronicObserver) repository. It's the resx files which we edit with [resx manager](https://github.com/dotnet/ResXResourceManager).

In resx manager it looks something like this, and all you need to do to generate the files is double-click the empty cell in the ko-KR column.
![image](https://github.com/ElectronicObserverEN/Data/assets/40002167/04c7a501-7c78-45e8-addf-f62a3285b012)

Editing the files manually will be a bit harder, but I can generate them if you prefer it that way.

**Comment by MirhasVida** [comment]
> > I've added it, but please let me know if there are still problems.
> 
> I don't see any changes related to that, where did you add it?
> 
> > Btw I cannot find any translation files for the UI Could you make it for me?
> 
> The UI translations are in the [Electronic Observer](https://github.com/ElectronicObserverEN/ElectronicObserver) repository. It's the resx files which we edit with [resx manager](https://github.com/dotnet/ResXResourceManager).
> 
> In resx manager it looks something like this, and all you need to do to generate the files is double-click the empty cell in the ko-KR column. ![image](https://private-user-images.githubusercontent.com/40002167/331260720-04c7a501-7c78-45e8-addf-f62a3285b012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzIzNTIsIm5iZiI6MTcxNTg3MjA1MiwicGF0aCI6Ii80MDAwMjE2Ny8zMzEyNjA3MjAtMDRjN2E1MDEtN2M3OC00NWU4LWFkZGYtZjYyYTMyODViMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGFlMGIyNzM5NzU0NjFhNGE4MzhkYWRlZDg2ODQ3NjI2ZDA2YTk2ZmQ0NDI3Nzk3NzQ3OTZlYjQxNTBjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6ZqyIhX8DW4lCs2CBF9uGm2JHxzWvWnR4MPGI-lD0U)
> 
> Editing the files manually will be a bit harder, but I can generate them if you prefer it that way.

What about now? I've resynced it.

**Comment by myangelkamikaze** [comment]
I think you deleted something? The changes can be seen [here](https://github.com/ElectronicObserverEN/Data/tree/2018f5db3838780023c354f5eca8513046a8e6a7), but they don't seem to belong to any repository.
You might need to copy all the changes you did there back to your repository.

**Comment by MirhasVida** [comment]
Oh lord, thanks a lot! I am not used to GitHub, so I clicked some random thing to solve the crashes, and all gone in a sudden. I was totally panicked lmao

**Comment by myangelkamikaze** [comment]
Yeah, git can be a bit confusing if you're not familiar with it. I get confused fairly often, too.

**Comment by MirhasVida** [comment]
I made a new PR, check it out and let me know if there are any conflicts.

FWI, I can check your comments from 9 AM to 1 AM in KST.

**Comment by myangelkamikaze** [comment]
Yeah, I merged it already, thank you.
I'm generally available during those times so that should work out.

We also have a discord server, we usually notice messages faster there than here on GitHub.
![image](https://github.com/ElectronicObserverEN/Data/assets/40002167/29616fb3-18eb-47b2-a419-08d058c73bc4)
