### ISSUE TITLE
How to add new language?

### ISSUE THREAD

**Issue by Blueberryy** [ElectronicObserverEN/Data#9]
I'd like to know for future how do i do that?

**Comment by myangelkamikaze** [comment]
Sorry for the slow reply.
Add a new folder named after the language you're trying to add [here](https://github.com/ElectronicObserverEN/Data/tree/master/Translations) (I'm guessing ru-RU?).
After that, we just need to add support for it in the [EO repo](https://github.com/ElectronicObserverEN/ElectronicObserver).
Note that this repo doesn't contain all the translations, it's mostly translations related to game data itself, such as ship names, quests etc.
For translations for EO itself, that's handled via resx files in the EO repo.

**Comment by Blueberryy** [comment]
> Sorry for the slow reply. Add a new folder named after the language you're trying to add [here](https://github.com/ElectronicObserverEN/Data/tree/master/Translations) (I'm guessing ru-RU?). After that, we just need to add support for it in the [EO repo](https://github.com/ElectronicObserverEN/ElectronicObserver). Note that this repo doesn't contain all the translations, it's mostly translations related to game data itself, such as ship names, quests etc. For translations for EO itself, that's handled via resx files in the EO repo.

Thanks for info. It would be useful if you can add this to readme or somewhere so people will know how to do that.
